import { MainStatKey, SubstatKey } from "go/Types/artifact";
import { ArtifactSetKey, SlotKey } from "go/Types/consts";

type ArtifactSet = { [key in SlotKey]: string };

export const ARTIFACT_DISPLAY_NAMES: {
  [key in ArtifactSetKey]?: ArtifactSet;
} = {
  Adventurer: {
    flower: "Adventurer's Flower",
    plume: "Adventurer's Tail Feather",
    sands: "Adventurer's Pocket Watch",
    goblet: "Adventurer's Golden Goblet",
    circlet: "Adventurer's Bandana",
  },
  ArchaicPetra: {
    flower: "Flower of Creviced Cliff",
    plume: "Feather of Jagged Peaks",
    sands: "Sundial of Enduring Jade",
    goblet: "Goblet of Chiseled Crag",
    circlet: "Mask of Solitude Basalt",
  },
  Berserker: {
    flower: "Berserker's Rose",
    plume: "Berserker's Indigo Feather",
    sands: "Berserker's Timepiece",
    goblet: "Berserker's Bone Goblet",
    circlet: "Berserker's Battle Mask",
  },
  BlizzardStrayer: {
    flower: "Snowswept Memory",
    plume: "Icebreaker's Resolve",
    sands: "Frozen Homeland's Demise",
    goblet: "Frost-Weaved Dignity",
    circlet: "Broken Rime's Echo",
  },
  BloodstainedChivalry: {
    flower: "Bloodstained Flower of Iron",
    plume: "Bloodstained Black Plume",
    sands: "Bloodstained Final Hour",
    goblet: "Bloodstained Chevalier's Goblet",
    circlet: "Bloodstained Iron Mask",
  },
  BraveHeart: {
    flower: "Medal of the Brave",
    plume: "Prospect of the Brave",
    sands: "Fortitude of the Brave",
    goblet: "Outset of the Brave",
    circlet: "Crown of the Brave",
  },
  CrimsonWitchOfFlames: {
    flower: "Witch's Flower of Blaze",
    plume: "Witch's Ever-Burning Plume",
    sands: "Witch's End Time",
    goblet: "Witch's Heart Flames",
    circlet: "Witch's Scorching Hat",
  },
  DeepwoodMemories: {
    flower: "Labyrinth Wayfarer",
    plume: "Scholar of Vines",
    sands: "A Time of Insight",
    goblet: "Lamp of the Lost",
    circlet: "Laurel Coronet",
  },
  DefendersWill: {
    flower: "Guardian's Flower",
    plume: "Guardian's Sigil",
    sands: "Guardian's Clock",
    goblet: "Guardian's Vessel",
    circlet: "Guardian's Band",
  },
  EchoesOfAnOffering: {
    flower: "Soulscent Bloom",
    plume: "Jade Leaf",
    sands: "Symbol of Felicitation",
    goblet: "Chalice of the Font",
    circlet: "Flowing Rings",
  },
  EmblemOfSeveredFate: {
    flower: "Magnificent Tsuba",
    plume: "Sundered Feather",
    sands: "Storm Cage",
    goblet: "Scarlet Vessel",
    circlet: "Ornate Kabuto",
  },
  Gambler: {
    flower: "Gambler's Brooch",
    plume: "Gambler's Feather Accessory",
    sands: "Gambler's Pocket Watch",
    goblet: "Gambler's Dice Cup",
    circlet: "Gambler's Earrings",
  },
  GildedDreams: {
    flower: "Shadow of the Sand King",
    plume: "Honeyed Final Feast",
    sands: "The Sunken Years",
    goblet: "Feather of Judgment",
    circlet: "Dreaming Steelbloom",
  },
  GladiatorsFinale: {
    flower: "Gladiator's Nostalgia",
    plume: "Gladiator's Destiny",
    sands: "Gladiator's Longing",
    goblet: "Gladiator's Intoxication",
    circlet: "Gladiator's Triumphus",
  },
  HeartOfDepth: {
    flower: "Gilded Corsage",
    plume: "Gust of Nostalgia",
    sands: "Copper Compass",
    goblet: "Goblet of Thundering Deep",
    circlet: "Wine-Stained Tricorne",
  },
  HuskOfOpulentDreams: {
    flower: "Bloom Times",
    plume: "Plume of Luxury",
    sands: "Song of Life",
    goblet: "Calabash of Awakening",
    circlet: "Skeletal Hat",
  },
  Instructor: {
    flower: "Instructor's Brooch",
    plume: "Instructor's Feather Accessory",
    sands: "Instructor's Pocket Watch",
    goblet: "Instructor's Tea Cup",
    circlet: "Instructor's Cap",
  },
  Lavawalker: {
    flower: "Lavawalker's Resolution",
    plume: "Lavawalker's Salvation",
    sands: "Lavawalker's Torment",
    goblet: "Lavawalker's Epiphany",
    circlet: "Lavawalker's Wisdom",
  },
  LuckyDog: {
    flower: "Lucky Dog's Clover",
    plume: "Lucky Dog's Eagle Feather",
    sands: "Lucky Dog's Hourglass",
    goblet: "Lucky Dog's Goblet",
    circlet: "Lucky Dog's Silver Circlet",
  },
  MaidenBeloved: {
    flower: "Maiden's Distant Love",
    plume: "Maiden's Heart-Stricken Infatuation",
    sands: "Maiden's Passing Youth",
    goblet: "Maiden's Fleeting Leisure",
    circlet: "Maiden's Fading Beauty",
  },
  MartialArtist: {
    flower: "Martial Artist's Red Flower",
    plume: "Martial Artist's Feather Accessory",
    sands: "Martial Artist's Water Hourglass",
    goblet: "Martial Artist's Wine Cup",
    circlet: "Martial Artist's Bandana",
  },
  NoblesseOblige: {
    flower: "Royal Flora",
    plume: "Royal Plume",
    sands: "Royal Pocket Watch",
    goblet: "Royal Silver Urn",
    circlet: "Royal Masque",
  },
  OceanHuedClam: {
    flower: "Sea-Dyed Blossom",
    plume: "Deep Palace's Plume",
    sands: "Cowry of Parting",
    goblet: "Pearl Cage",
    circlet: "Crown of Watatsumi",
  },
  PaleFlame: {
    flower: "Stainless Bloom",
    plume: "Wise Doctor's Pinion",
    sands: "Moment of Cessation",
    goblet: "Surpassing Cup",
    circlet: "Mocking Mask",
  },
  ResolutionOfSojourner: {
    flower: "Heart of Comradeship",
    plume: "Feather of Homecoming",
    sands: "Sundial of the Sojourner",
    goblet: "Goblet of the Sojourner",
    circlet: "Crown of Parting",
  },
  RetracingBolide: {
    flower: "Summer Night's Bloom",
    plume: "Summer Night's Finale",
    sands: "Summer Night's Moment",
    goblet: "Summer Night's Waterballoon",
    circlet: "Summer Night's Mask",
  },
  Scholar: {
    flower: "Scholar's Bookmark",
    plume: "Scholar's Quill Pen",
    sands: "Scholar's Clock",
    goblet: "Scholar's Ink Cup",
    circlet: "Scholar's Lens",
  },
  ShimenawasReminiscence: {
    flower: "Entangling Bloom",
    plume: "Shaft of Remembrance",
    sands: "Morning Dew's Moment",
    goblet: "Hopeful Heart",
    circlet: "Capricious Visage",
  },
  TenacityOfTheMillelith: {
    flower: "Flower of Accolades",
    plume: "Ceremonial War-Plume",
    sands: "Orichalceous Time-Dial",
    goblet: "Noble's Pledging Vessel",
    circlet: "General's Ancient Helm",
  },
  TheExile: {
    flower: "Exile's Flower",
    plume: "Exile's Feather",
    sands: "Exile's Pocket Watch",
    goblet: "Exile's Goblet",
    circlet: "Exile's Circlet",
  },
  ThunderingFury: {
    flower: "Thunderbird's Mercy",
    plume: "Survivor of Catastrophe",
    sands: "Hourglass of Thunder",
    goblet: "Omen of Thunderstorm",
    circlet: "Thunder Summoner's Crown",
  },
  Thundersoother: {
    flower: "Thundersoother's Heart",
    plume: "Thundersoother's Plume",
    sands: "Hour of Soothing Thunder",
    goblet: "Thundersoother's Goblet",
    circlet: "Thundersoother's Diadem",
  },
  TinyMiracle: {
    flower: "Tiny Miracle's Flower",
    plume: "Tiny Miracle's Feather",
    sands: "Tiny Miracle's Hourglass",
    goblet: "Tiny Miracle's Goblet",
    circlet: "Tiny Miracle's Earrings",
  },
  TravelingDoctor: {
    flower: "Traveling Doctor's Silver Lotus",
    plume: "Traveling Doctor's Owl Feather",
    sands: "Traveling Doctor's Pocket Watch",
    goblet: "Traveling Doctor's Medicine Pot",
    circlet: "Traveling Doctor's Handkerchief",
  },
  VermillionHereafter: {
    flower: "Flowering Life",
    plume: "Feather of Nascent Light",
    sands: "Solar Relic",
    goblet: "Moment of the Pact",
    circlet: "Thundering Poise",
  },
  ViridescentVenerer: {
    flower: "In Remembrance of Viridescent Fields",
    plume: "Viridescent Arrow Feather",
    sands: "Viridescent Venerer's Determination",
    goblet: "Viridescent Venerer's Vessel",
    circlet: "Viridescent Venerer's Diadem",
  },
  WanderersTroupe: {
    flower: "Troupe's Dawnlight",
    plume: "Bard's Arrow Feather",
    sands: "Concert's Final Hour",
    goblet: "Wanderer's String-Kettle",
    circlet: "Conductor's Top Hat",
  },
};

export const MAINSTAT_DISPLAY_NAMES: { [key: string]: MainStatKey } = {
  HP: "hp_",
  ATK: "atk_",
  DEF: "def_",
  "Elemental Mastery": "eleMas",
  "Energy Recharge": "enerRech_",
  "CRIT Rate": "critRate_",
  "CRIT DMG": "critDMG_",
  "Physical DMG Bonus": "physical_dmg_",
  "Anemo DMG Bonus": "anemo_dmg_",
  "Geo DMG Bonus": "geo_dmg_",
  "Electro DMG Bonus": "electro_dmg_",
  "Hydro DMG Bonus": "hydro_dmg_",
  "Pyro DMG Bonus": "pyro_dmg_",
  "Cryo DMG Bonus": "cryo_dmg_",
  "Dendro DMG Bonus": "dendro_dmg_",
  "Healing Bonus": "heal_",
};

export const SUBSTAT_DISPLAY_NAMES: {
  [key: string]: [SubstatKey, SubstatKey];
} = {
  HP: ["hp", "hp_"],
  ATK: ["atk", "atk_"],
  DEF: ["def", "def_"],
  "Elemental Mastery": ["eleMas", "eleMas"],
  "Energy Recharge": ["enerRech_", "enerRech_"],
  "CRIT Rate": ["critRate_", "critRate_"],
  "CRIT DMG": ["critDMG_", "critDMG_"],
};
